name: cas client

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [test]
  pull_request:
    branches: [test]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  client:
    runs-on: ubuntu-latest
    environment: 
      name: production

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'

      - name: Install npm dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to Staging My server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.MY_SERVER_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./dist/*"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }} #服务器ip
          REMOTE_USER: "root"
          TARGET: "/project/nginx_cas/html/"
          EXCLUDE: "/node_modules/"
